### ISSUE TITLE
 No fallback if job committer_date is null/empty

### ISSUE THREAD

**Issue by jmsbrcwll** [eddiewebb/circleci-queue#101]
### RELEASE CANDIDATE READY

➡️ **Potential fix for this issue is ready** ⬅️

For anyone willing to validate on non-critical workloads, please use `eddiewebb/queue@dev:506` and report any issues on #112 

---

### Orb version 
2.2.1

### What happened
I am using a bitbucket repo for my project, and it looks like the committer_date field, which is used to determine which jobs are oldest is always empty. It would be good if there was an option/fallback to use build number in this case - especially since I also have uses cases to queue jobs that are manually triggered with parameters, i.e. without a new commit push

### Expected behavior

Should still be able to queue jobs when committer_date is empty

**Comment by eddiewebb** [comment]
We'll have to figure out how to support BB users who also are talking advantage of dynamic config where the workflow level timing is not sufficient. 

There has been substantial API work since initial issues so we might be able to get pipeline level timing without commiter date.

**Comment by eddiewebb** [comment]
### ATTENTION

Please see #112  as possible resolution
