### ISSUE TITLE
[2.2.1] ERROR: Server returned error code: 404

### ISSUE THREAD

**Issue by maven2016** [eddiewebb/circleci-queue#106]
### What happened

Env var CIRCLECI_API_KEY is set.
workflow queue fails with next error:

ERROR: Server returned error code: 404
{
  "message" : "{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/repos/repos#get-a-repository\"}"
}

### Expected behavior

block concurrent workflow execution on same branch

**Comment by eddiewebb** [comment]
This is an error talking to Github, much more information is needed.

Cloud or server? 
What VCS?
Had it ever worked for you (another verion, etc)?
Job or command (if iwilling config snippet)
LOg OUput
