### ISSUE TITLE
[2.2.1] gitlab - does not support CIRCLE_PROJECT_REPONAME

### ISSUE THREAD

**Issue by blahetal** [eddiewebb/circleci-queue#109]
### Orb version

2.2.1

### What happened

circleci does not support CIRCLE_PROJECT_REPONAME for gitlab, there is a workaround to define it in your circleci script as

```
environment:
      CIRCLE_PROJECT_REPONAME: << pipeline.trigger_parameters.gitlab.repo_name >>
```

but this does not work with orbs, could you add a new setting to provide repo name from outside

### Expected behavior

the orb should fetch repo name from a parameter in case of gitlab

**Comment by eddiewebb** [comment]
> but this does not work with orbs, could you add a new setting to provide repo name from outside

in the interim a pre-step should work, as long as you save to $BASH_ENV for subsequent steps.

Long term this will be a good 3.0 inclusion.

**Comment by eddiewebb** [comment]
🎉  even better, our R&D shipped a fix for github app and gitlab so that VAR now has values. (Jan 5)
