### ISSUE TITLE
Git tags

### ISSUE THREAD

**Issue by iynere** [eddiewebb/circleci-queue#16]
Would love for this to work with git tags. Git tag-triggered jobs don't have `$CIRCLE_BRANCH` set :/

**Comment by eddiewebb** [comment]
Ah interesting. This should still work and would just block across all builds, which as long as  consider-branch is false. 

We'd just need to remove the empty variable check or wrap that in an ' if [ consider-branch == true  ]`

(Abbreviated message Sent from phone)

**Comment by eddiewebb** [comment]
This should be fixed, and if i can't get a fix for #19 figured in the next few days I ship it alone.

**Comment by iynere** [comment]
thank you ! @eddiewebb i haven't gotten a chance to look @ this yet but will do that tomorrow

**Comment by iynere** [comment]
feel free to ship anything w/o my 👀 tho @eddiewebb

**Comment by eddiewebb** [comment]
Went live in #20 , I'm going to rev to 1.1 shortly

**Comment by iynere** [comment]
oy, ty, i never looked @ this but glad it got fixed ^_^

**Comment by alonisser** [comment]
@eddiewebb just happened to me with the latest. so I think it's not fixed
Broken when pushing tags
I don't have any branch setup in the job and default is supposed to be * (from the docs) which is all I believe

> environment: line 25: CIRCLE_BRANCH: Required Env Variable not found!

**Comment by cjmosure** [comment]
Same, I am getting 

```
Block: false
environment: line 28: MY_BRANCH: Required MY_BRANCH not found! This is likely a bug in orb, please report.

Exited with code exit status 127
```

On latest, if my workflow is triggered by a tag. For example using a CircleCI filter like (v123):

```
  filters:
    tags:
      only: /^v\d+/
    branches:
      ignore: /.*/
```

**Comment by eddiewebb** [comment]
Version 3 overhauled all this logic, but fix is simple, it's just checking to aggressively. 

Should be able to look this week.
