### ISSUE TITLE
circleci-queue doesn't support workflow isolation

### ISSUE THREAD

**Issue by glentakahashi** [eddiewebb/circleci-queue#19]
As per our discussion, right now if multiple workflows are queued at the same time, it's possible that the circleci-queue job doesn't block the workflow until other workflows are stopped. This is because within a workflow, job ids are not assigned at start time, but at runtime. 
Visual example if you queue two workflows right after the other, where A=the block_workflow job, the job ids will look like:
   A'(2)   B'     C'
A(1)    B      C

Since A(1) is at the front of the queue, it will finish successfully instantly, and then begin executing B, which now gets the id B(3). Next, since A'(2) is now at the front of the queue, it will also finish successfully, and queue up B' which now gets the id B'(4). At this point you will have two B jobs concurrently running.

**Comment by eddiewebb** [comment]
Looking at the API, I think `all_commit_details.committer_date` would be a suitable way to enforce authoritative ordering at the workflow level.     I need to confirm this information is available consistently, including tag-triggered workflows.

**Comment by eddiewebb** [comment]
Actually, thinking about this more..

Build ID might still be suitable *IF* the initial job knows it needs to look at the entire workflow.

>Since A(1) is at the front of the queue, it will finish successfully instantly, and then begin executing B, which now gets the id B(3). 
Holds true.
>Next, since A'(2) is now at the front of the queue, it will also finish successfully,
If the logic for all jobs A knew it needed to look at the workflow, it should see that B(3) is running, which not being higher than 2 will force it to wait still.

Can you confirm that you had `consider-job: false` in your setup?

**Comment by eddiewebb** [comment]
@glentakahashi  - can you confirm use of `consider-job: false` while I dig into this? Our API does appear to order by build_num which would mean we would potentially need additional logic to re-sort based on timestamps.

**Comment by glentakahashi** [comment]
@eddiewebb yep, tested it with both `consider-job: false` and `consider-job: true`
The issue still persists, because if `block_workflow` is the 1st job in a workflow, jobId's for that job will be associated instantly, regardless if they are queued or running (because I believe circleci associates jobids to jobs in a workflow once they're next in line to be run) You will still end up with scenarios where `deploy` or other jobs scheduled after will still have larger jobid's, and thus cause A and A' to both pass.

One nice way to fix this (but relies on apis that don't exist yet) is to instead of comparing Job ID's, instead compare workflow ID's. If there were an endpoint like `/workflows` that could be sorted by start time, then you could have https://github.com/eddiewebb/circleci-queue/blob/master/src/commands/until_front_of_line.yml#L85 do an `oldest=\`jq '.[-1].workflow_id' /tmp/workflowstatus.json\``, and have https://github.com/eddiewebb/circleci-queue/blob/master/src/commands/until_front_of_line.yml#L121 do a `if [ ${CIRCLE_WORKFLOW_ID} = $oldest_running_workflow_id ]; then` instead.

That way this job would queue until the oldest running workflow had the same id as the workflow that contained the currently running job.

**Comment by eddiewebb** [comment]
The idea of workflow numbering (~~as oppose~~ _in addition_ to UUIDs) is current _planned_
https://circleci.com/ideas/?idea=CCI-I-348 (We encourage voting for anyone interested in this general features)

But until then I guess best best is to try get start time of the first job in all workflows with an active job, or attempt to use the committer timestamp which should represent order, and be consistent in all jobs across a workflow. (though need to confirm how different PR merge types look)

**Comment by eddiewebb** [comment]
#20 sorts all runnings jobs by their committer time, and will proceed once it is the oldest.

it also replaces `consider-job` with more aptly names `block-workflow`

**Comment by eddiewebb** [comment]
Released best I can do given API constraints in 1.1.0 https://circleci.com/orbs/registry/orb/eddiewebb/queue

**Comment by eddiewebb** [comment]
Oh, and be sure to set `consider-branch` to false if you want to queue across branches (would love feedback, but currently assumes feature branches and such are safe to run concurrently by default)

**Comment by glentakahashi** [comment]
Will give this a shot tomorrow! thanks for the fast turnaround!

**Comment by tberman** [comment]
So I have a multistep job workflow (as follows)

1. queue
2. build
3. deploy

and I have definitely seen the queue step allow a transition on Workflow 2 when going from 2 to 3 on Workflow 1. What kind of data can I grab to help debug?

**Comment by eddiewebb** [comment]
@tberman - I think you're seeing something different, and opened #26
