### ISSUE TITLE
Job block-workflow doesn't use block-workflow parameter

### ISSUE THREAD

**Issue by jarikujansuu** [eddiewebb/circleci-queue#28]
Parameter `block-workflow` is not used at all. It works correctly because command `until_front_of_line` checks legacy parameter `consider-job`

Spotted when was trying to figure out error which was probably #26

**Comment by Sai-Adarsh** [comment]
@jarikujansuu I'll start fixing this. BTW, could you add _working_ label to this issue?

**Comment by eddiewebb** [comment]
Job block-workflow doesn't use block-workflow parameter because using the job level invocation implies you want to block the workflow, so it passes a true to the command. They command does use this parameter. Closing issue.
