### ISSUE TITLE
Feature Request: Parameterize CIRCLECI_API_KEY env var

### ISSUE THREAD

**Issue by philnielsen** [eddiewebb/circleci-queue#56]
Minor Feature request, would you be interested in a PR that makes `CIRCLECI_API_KEY` an env-var parameter (with `CIRCLECI_API_KEY` as default) so we could pass in a different one? Our team's contexts use a different API key env var so it would be nice to just pass that in instead of having it to change in all our scripts! 

Thanks for the good orb, we really need this ability in circleci by default!

**Comment by eddiewebb** [comment]
That'd be a welcome contribution! Thanks for raising this
