### ISSUE TITLE
Orb Uses Unauthenticated Dockerhub Pull

### ISSUE THREAD

**Issue by philnielsen** [eddiewebb/circleci-queue#60]
### Orb version
1.5.0

### What happened
Starting Nov 1st dockerhub is going to rate limit unauthenticated docker image pulls. CircleCI emits a warning when using un-auth'ed pulls: 
```
Warning: No authentication provided, this pull may be subject to Docker Hub download rate limits. 
```

### Expected behavior
Probably add the ability to use authenticated pulls in the orb executor. or the ability to override the executer with a parameter.

**Comment by eddiewebb** [comment]
The orb itself is not responsible for pulling images, which happens by circleCI run agent. And as of this writing CircleCI will use their own credentials if customer credentials are not provided in top level config.
