### ISSUE TITLE
"Ghost" jobs (with SSH session open) keeps queue always blocked

### ISSUE THREAD

**Issue by pacoard** [eddiewebb/circleci-queue#61]
### What happened

Trying out this orb for the first time, for some reason I see that, within my builds, the number `380` was skipped (probs a CircleCI bug? ), and this number is detected by the queue orb as if it was still running, rendering the next deployments useless since they THINK there's a build still running.

All branches and everyone's pipelines are selected, so there are no filters that could hide that missing `380`
![image](https://user-images.githubusercontent.com/12046663/101727320-1ef0b280-3a69-11eb-9bfb-4f8456a5935c.png)

![image](https://user-images.githubusercontent.com/12046663/101727116-b73a6780-3a68-11eb-933d-38bf4e86a94b.png)

![image](https://user-images.githubusercontent.com/12046663/101727422-4cd5f700-3a69-11eb-899d-37808845a117.png)

### Expected behavior

380 doesn't exist or it is not running, therefore the queue shouldn't be blocked!

I wonder if this is an uncaught error that could be solved from this orb's end

**Comment by pacoard** [comment]
## UPDATE

Turns out that the job `380` was stuck because I rerun it with an SSH session, which keeps the job running for 2h if you don't exit the SSH session.

Leaving this issue open anyway, but I'll change the title to account for this

**Comment by eddiewebb** [comment]
Thanks for reporting @pacoard 

To wait for SSH jobs feels valid to me since SSH jobs still perform all steps, which could clash with other non-ssh jobs running the same tasks.
