### ISSUE TITLE
[semver:patch] tag-pattern condition syntax error

### ISSUE THREAD

**Issue by calvin-cdev** [eddiewebb/circleci-queue#67]
### Orb version
1.6.0

### What happened

using the `tag-pattern` param, getting an from erroneous syntax
```
environment: line 23: [: missing `]'
```

caused by the line 
```
[ -n "${CIRCLE_TAG:x}" && "<<parameters.tag-pattern>>" != "" ]
```

### Expected behavior

the condition check shouldn't error

I'm going to open a PR to fix this shortly and will update this description with a link to the PR.

**Comment by eddiewebb** [comment]
Thanks for report and fix @calvin-summer !

Published as `eddiewebb\queue@1.6.1`
