### ISSUE TITLE
Block running single workflow parallel for any branch

### ISSUE THREAD

**Issue by dcheng666666** [eddiewebb/circleci-queue#69]
**Is your feature request related to a problem? Please describe.**

We are doing Salesforce development, and we have different workflows used by different teams, we want different workflows can be running independently, but within single workflow, we want all commits at any branches running serially since each workflow has only one sandbox environment to run.
Right now seem we can only block workflows on the same branches or on all branches, neither meets our requirement.

**Comment by eddiewebb** [comment]
You should be able to provide a branch name, a job name, and block_workflows=false.
