### ISSUE TITLE
[semver:minor] Expose an env variable that fails the workflow instead of cancel

### ISSUE THREAD

**Issue by moekify** [eddiewebb/circleci-queue#77]
**Is your feature request related to a problem? Please describe.**
I want to send a notification to slack whenever the orb cancels a workflow. However, currently it is not possible that the slack notifier works on cancel. There seems to be a difference between cancel and fail

**Describe the solution you'd like**
With the use of a parameter in the command allow to fail the workflow instead of cancel.

**Describe alternatives you've considered**
Get circleci to expose a on_cancel event.

**Comment by eddiewebb** [comment]
Love this.

**Comment by eddiewebb** [comment]
@pguinard-public-com  fixed this in #115 !

3.1.x +
