### ISSUE TITLE
Orb is gone from CircleCI store

### ISSUE THREAD

**Issue by snovity** [eddiewebb/circleci-queue#83]
It just disappeared

![image](https://user-images.githubusercontent.com/956399/191624912-df0760f3-9b50-435f-9426-3b9099aa74eb.png)

![image](https://user-images.githubusercontent.com/956399/191624859-de19be43-2bb7-4fd6-bb71-2914116f7c07.png)

**Comment by eddiewebb** [comment]
Must have been a platform issue. I'm still here.
https://circleci.com/developer/orbs/orb/eddiewebb/queue

**Comment by snovity** [comment]
Yep, it's back! Thank you for your great work :pray:
