### ISSUE TITLE
[semver:patch] add "Content-Type: application/json" to all curl requests

### ISSUE THREAD

**Issue by michw** [eddiewebb/circleci-queue#85]
### Orb version

1.7.0

### What happened

Circleci's api stopped working.

I.e. response:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 4JEGQSiUPEc8KRujDuFT2XCMaHpV-1234567890==
</PRE>
<ADDRESS>
</ADDRESS>
* Connection #0 to host circleci.com left intact
</BODY></HTML>
```

### Expected behavior

Lets add `-H "Content-Type: application/json"` to all `curl` requests in the `src/` Circleci's api reponse should be visible

**Comment by bryan-lee-git** [comment]
Same issue here!

**Comment by bryan-lee-git** [comment]
Confirmed that adding `-H "Content-Type: application/json"` fixes the api call issue on our end as well.

**Comment by michw** [comment]
Fwiw, I can reproduce it only by sshing into circleci worker.

When accessing circleci's api from my local computer -- it works fine with or without 'Content-type' header.

**Comment by bryan-lee-git** [comment]
> Fwiw, I can reproduce it only by sshing into circleci worker.
> 
> When accessing circleci's api from my local computer -- it works fine with or without 'Content-type' header.

I get a success when running the curl that includes ` -H "Content-Type: application/json"` when ssh'd into a circle machine or on my host. Fails without in both places for me.

**Comment by kevinr-electric** [comment]
I'm seeing the same failures (locally and SSH'ed), and adding the header seems to fix it for me too. Can't seem to find any place in CircleCI documentation mentioning this header being required, but I haven't looked that hard.

Just put up [PR 86](https://github.com/eddiewebb/circleci-queue/pull/86) to address it.

**Comment by SethAdamson** [comment]
Looks like CircleCI fixed the issue and we dont need to the header to get successful responses now

**Comment by kevinr-electric** [comment]
We are seeing the job pass again, and the endpoint is working for me without the header now as well. I'm guessing CircleCI noticed and rolled back whatever change required the header 🤷 

Leaving the PR up because it still might be a change CircleCI applies in the future, and adding the header doesn't seem to hurt anything.

**Comment by bryan-lee-git** [comment]
<img width="630" alt="Screen Shot 2022-10-28 at 10 42 14 AM" src="https://user-images.githubusercontent.com/36904794/198689255-07124170-6189-44b9-b4bc-8aa789e75772.png">
<img width="625" alt="Screen Shot 2022-10-28 at 10 42 08 AM" src="https://user-images.githubusercontent.com/36904794/198689260-09305892-d7c8-4340-982b-3ca052b05fdb.png">

**Comment by eddiewebb** [comment]
YOU ALL ARE AMAZING

(sorrty for delay, patch in merging now)

**Comment by eddiewebb** [comment]
versions `1.7.1` and `1.8+` include the new header and will also print messages on server errors for troubleshooting.
